In [16]:
# PCA降维，通过矩阵运算

import numpy as np
import sklearn.datasets as datasets
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [4]:
iris=datasets.load_iris()
X=iris["data"]
y=iris["target"]

In [6]:
X.shape

(150, 4)

In [8]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
# whiten  是对数据进行了Standard 归一化
s=StandardScaler()
pca=PCA(n_components=0.95,whiten=False)
X_pca=pca.fit_transform(X)
s.fit_transform(X_pca)

array([[-1.30971087,  0.65054141],
       [-1.32435711, -0.36051227],
       [-1.40967409, -0.29522986],
       [-1.33958163, -0.64830449],
       [-1.33146886,  0.66552653],
       [-1.11293846,  1.50992585],
       [-1.37627274, -0.18221302],
       [-1.28141939,  0.33277896],
       [-1.4084016 , -1.17789289],
       [-1.30416299, -0.23173293],
       [-1.22325714,  1.3138624 ],
       [-1.2748859 ,  0.03000162],
       [-1.35947347, -0.47887104],
       [-1.57304515, -1.04159745],
       [-1.29049784,  2.40088235],
       [-1.16426043,  2.72533645],
       [-1.28014238,  1.65117453],
       [-1.29222826,  0.6351676 ],
       [-1.07339558,  1.7777797 ],
       [-1.26280003,  1.04600854],
       [-1.12728243,  0.79708495],
       [-1.24119316,  0.88191703],
       [-1.56920777,  0.27184488],
       [-1.12361159,  0.20104806],
       [-1.14948296, -0.07593489],
       [-1.2231214 , -0.29740403],
       [-1.20465318,  0.26671917],
       [-1.25027614,  0.74896183],
       [-1.28795287,

In [21]:
pca=PCA(n_components=0.95,whiten=True)
X_pca=pca.fit_transform(X)
X_pca

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [22]:
# 1. 去中心化
# 2. 协方差
# 3. 特征值和特征向量计算
# 4. 从特征值中选取白分比大于95%的特征所对应的特征向量
# 5. 使用选取数来的特征向量进行矩阵运算


In [33]:
# 1. 去中心化
A=X-X.mean(axis=0)
A

array([[-7.43333333e-01,  4.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01, -5.73333333e-02, -2.35800000e+00,
        -9.99333333e-01],
       [-1.14333333e+00,  1.42666667e-01, -2.45800000e+00,
        -9.99333333e-01],
       [-1.24333333e+00,  4.26666667e-02, -2.25800000e+00,
        -9.99333333e-01],
       [-8.43333333e-01,  5.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-4.43333333e-01,  8.42666667e-01, -2.05800000e+00,
        -7.99333333e-01],
       [-1.24333333e+00,  3.42666667e-01, -2.35800000e+00,
        -8.99333333e-01],
       [-8.43333333e-01,  3.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.44333333e+00, -1.57333333e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01,  4.26666667e-02, -2.25800000e+00,
        -1.09933333e+00],
       [-4.43333333e-01,  6.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.04333333e+00,  3.42666667e-01, -2.15800000e+00,
      

In [36]:
# 2. 协方差
V=np.cov(A,rowvar=False)
V

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [42]:
# 3. 特征值和特征向量计算

T,TV=np.linalg.eig(V)
print(T,TV)

[4.22824171 0.24267075 0.0782095  0.02383509] [[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [54]:
#   选取前两个的特性向量
#  4. 从特征值中选取白分比大于95%的特征所对应的特征向量
P=TV[:,[0,1]]
# 5. 使用选取数来的特征向量进行矩阵运算
s=StandardScaler()
s.fit_transform(X.dot(P))

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653],
       [-1.11293846, -1.50992585],
       [-1.37627274,  0.18221302],
       [-1.28141939, -0.33277896],
       [-1.4084016 ,  1.17789289],
       [-1.30416299,  0.23173293],
       [-1.22325714, -1.3138624 ],
       [-1.2748859 , -0.03000162],
       [-1.35947347,  0.47887104],
       [-1.57304515,  1.04159745],
       [-1.29049784, -2.40088235],
       [-1.16426043, -2.72533645],
       [-1.28014238, -1.65117453],
       [-1.29222826, -0.6351676 ],
       [-1.07339558, -1.7777797 ],
       [-1.26280003, -1.04600854],
       [-1.12728243, -0.79708495],
       [-1.24119316, -0.88191703],
       [-1.56920777, -0.27184488],
       [-1.12361159, -0.20104806],
       [-1.14948296,  0.07593489],
       [-1.2231214 ,  0.29740403],
       [-1.20465318, -0.26671917],
       [-1.25027614, -0.74896183],
       [-1.28795287,

In [53]:
# s.fit_transform(X.dot(np.linalg.eig(V)[-1][:,[2,3]]))

array([[-1.00151554e-01,  1.47034950e-02],
       [-7.55094180e-01,  6.43569895e-01],
       [ 6.42217285e-02,  1.29773828e-01],
       [ 1.13227291e-01, -4.91164442e-01],
       [ 3.23182218e-01, -3.98117332e-01],
       [ 6.05174059e-01, -1.57280480e-01],
       [ 9.25253800e-01, -3.12880272e-01],
       [-7.84976253e-02, -2.94389189e-01],
       [ 7.44802455e-02, -1.73813050e-01],
       [-7.09057735e-01, -3.65861735e-01],
       [-2.70222541e-01, -9.76139348e-02],
       [ 3.66490074e-01, -1.01630270e+00],
       [-7.42107075e-01, -5.12632456e-02],
       [ 2.19928187e-01, -1.40896297e-01],
       [-5.44002359e-01,  1.03469808e+00],
       [ 9.96595385e-01,  4.25782547e-02],
       [ 4.95767524e-01,  1.09010187e+00],
       [ 9.56793743e-02,  5.04502674e-01],
       [-4.31626705e-01,  1.75809092e-01],
       [ 7.66578223e-01, -4.30703507e-01],
       [-8.59066488e-01, -9.79445130e-02],
       [ 7.47893413e-01,  2.66882536e-01],
       [ 1.04904781e+00,  2.91291652e-02],
       [ 1.