### Basic constant operations  
### 常量操作


In [21]:
import numpy as np
import tensorflow as tf
tf.compat.v1.disable_eager_execution()


In [22]:
a=tf.constant(np.random.randint(0,10,size=(3,2)),dtype=tf.float32)
a

<tf.Tensor 'Const_4:0' shape=(3, 2) dtype=float32>

In [23]:
b=tf.constant(np.random.randint(0,10,size=(2,4)),dtype=np.float32)
b

<tf.Tensor 'Const_5:0' shape=(2, 4) dtype=float32>

In [24]:
# matrix multipy
c=tf.matmul(a,b)
c

<tf.Tensor 'MatMul_3:0' shape=(3, 4) dtype=float32>

In [30]:
with tf.compat.v1.Session() as sess:
    res=sess.run(c)
    print(res)

[[ 0. 27. 27. 54.]
 [18. 30. 38. 60.]
 [63. 48. 76. 96.]]


In [34]:
res.mean(axis=1)

array([27.  , 36.5 , 70.75], dtype=float32)

In [31]:
d=tf.reduce_mean(c,axis=1)
d

<tf.Tensor 'Mean_1:0' shape=(3,) dtype=float32>

In [33]:
with tf.compat.v1.Session() as sess:
    print(sess.run(d))

[27.   36.5  70.75]


### 变量赋值assign操作

In [39]:
a=np.random.randint(0,10,size=1)[0]
v=tf.Variable(initial_value=a)
v

<tf.Variable 'Variable_1:0' shape=() dtype=int32>

In [40]:
a

5

In [49]:
with tf.compat.v1.Session() as sess:
    # 变量必须进行初始化
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(v))

5


In [50]:
# 在 TensorFlow 2.0 中，assign 不再是 TensorFlow 包的函数，而是 tf.Variable 对象的方法
assign=v.assign(1024) 

In [53]:
with tf.compat.v1.Session() as sess:
    # 变量必须进行初始化
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(assign))
    print(sess.run(v))

1024
1024


### Basic Operations with variable as graph input  
### placeholder

In [60]:
# 占位符
A=tf.compat.v1.placeholder(dtype=tf.float32,shape=[3,5])
A

<tf.Tensor 'Placeholder_2:0' shape=(3, 5) dtype=float32>

In [59]:
# with tf.compat.v1.Session() as sess:
#     # 变量必须进行初始化
#     sess.run(tf.compat.v1.global_variables_initializer())
#     print(sess.run(A))


InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float and shape [3,5]
	 [[node Placeholder_1 (defined at <ipython-input-58-ddd804633051>:1) ]]

Original stack trace for 'Placeholder_1':
  File "D:\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\python\venv(data_analysis)\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "D:\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\Python\Python38\lib\asyncio\base_events.py", line 567, in run_forever
    self._run_once()
  File "D:\Python\Python38\lib\asyncio\base_events.py", line 1855, in _run_once
    handle._run()
  File "D:\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\kernelbase.py", line 358, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\kernelbase.py", line 536, in execute_request
    self.do_execute(
  File "d:\python\venv(data_analysis)\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\python\venv(data_analysis)\lib\site-packages\ipykernel\zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
    result = self._run_cell(
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "d:\python\venv(data_analysis)\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-ddd804633051>", line 1, in <module>
    A=tf.compat.v1.placeholder(dtype=tf.float32,shape=[3,5])
  File "d:\python\venv(data_analysis)\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3271, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "d:\python\venv(data_analysis)\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6744, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "d:\python\venv(data_analysis)\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "d:\python\venv(data_analysis)\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "d:\python\venv(data_analysis)\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)


In [61]:
B=tf.compat.v1.placeholder(dtype=tf.float32,shape=[5,None])
B

<tf.Tensor 'Placeholder_3:0' shape=(5, None) dtype=float32>

In [63]:
C=tf.matmul(A,B)
C

<tf.Tensor 'MatMul_5:0' shape=(3, None) dtype=float32>

In [67]:
with tf.compat.v1.Session() as sess:
    # 变量必须进行初始化
#     sess.run(tf.compat.v1.global_variables_initializer())
    res=sess.run(C,feed_dict={
        A:np.random.randint(0,10,size=(3,5)),
        B:np.random.randint(0,10,size=(5,5))
    })
    print(res)


[[123. 135. 105.  81.  60.]
 [217. 189. 164. 151. 145.]
 [ 69.  88. 102.  79.  43.]]


### 矩阵操作

### 使用TensorFlow根据graph完成运算
![](graph.jpg)

In [69]:
a=tf.constant(1)
b=tf.constant(2)
c=tf.compat.v1.placeholder(dtype=tf.int32,shape=None)
d=tf.Variable(initial_value=4)

In [72]:
add1=tf.add(a,b)
mul1=tf.multiply(b,c)
add2=tf.add(c,d)

In [75]:
out=tf.add(tf.add(add1,mul1),add2)
out

<tf.Tensor 'Add_9:0' shape=<unknown> dtype=int32>

In [78]:
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    res=sess.run(out,feed_dict={c:3})
    print(res)

    

16
