In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

In [6]:
data=np.array([[2,1,0,2,3],[9,5,4,2,0],[2,3,4,5,6],[1,2,3,1,0],[0,4,4,2,8]])
data

array([[2, 1, 0, 2, 3],
       [9, 5, 4, 2, 0],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 1, 0],
       [0, 4, 4, 2, 8]])

In [7]:
filter_=np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
filter_

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [18]:
"""
input,
filters,
strides,
padding,
data_format='NHWC',
dilations=None,
name=None,

"""
input_data=tf.reshape(tensor=data,shape=[1,5,5,1])

# input_data.astype(tf.float64)
input_data=tf.cast(input_data,dtype=tf.float32)
input_data
# input Computes a 2-D convolution given `input` and 4-D `filters` tensors.
# 1. Flattens the filter to a 2-D matrix with shape
#    `[filter_height * filter_width * in_channels, output_channels]`.
# padding: Either the `string` `"SAME"` or `"VALID"` indicating the type of
filters_=tf.cast(tf.reshape(tensor=filter_,shape=[3,3,1,1]),dtype=tf.float32)


conv=tf.nn.conv2d(input=input_data,filters=filters_,strides=[1,1,1,1],padding="VALID")
conv

<tf.Tensor 'Conv2D_1:0' shape=(1, 3, 3, 1) dtype=float32>

In [24]:
with tf.compat.v1.Session() as sess:
    res=sess.run(conv).reshape(3,3)
    print(res)

[[-5.  0.  1.]
 [-1. -2. -5.]
 [ 8. -1.  3.]]
