In [13]:
import numpy as np
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

In [14]:
a=np.random.randint(-5,10,size=20)
a

array([ 8,  8,  0,  3,  0, -4,  2,  7,  5,  7,  8,  1, -1,  3, -1,  8,  4,
        3,  2, -2])

In [15]:
b=tf.nn.relu(a)
b

<tf.Tensor 'Relu:0' shape=(20,) dtype=int32>

In [18]:
with tf.compat.v1.Session() as sess:
    res=sess.run(b)
    print(res)

[8 8 0 3 0 0 2 7 5 7 8 1 0 3 0 8 4 3 2 0]


In [20]:
c=tf.nn.relu6(a)
with tf.compat.v1.Session() as sess:
    res=sess.run(c)
    print(res)


[6 6 0 3 0 0 2 6 5 6 6 1 0 3 0 6 4 3 2 0]
